// Auto-generated by update_gallery.py
let mediaData = {
  "all": [
    {
      "type": "image",
      "src": "./assets/choreography/choreography.png",
      "title": "Choreography"
    },
    {
      "type": "image",
      "src": "./assets/creative-tools/creative_tools.png",
      "title": "Creative Tools"
    },
    {
      "type": "image",
      "src": "./assets/creative-tools/teaching_project_1.png",
      "title": "Teaching Project 1"
    },
    {
      "type": "image",
      "src": "./assets/curriculum-development/teaching_project_1.png",
      "title": "Teaching Project 1"
    },
    {
      "type": "image",
      "src": "./assets/experiential-learning/teaching_project_1.png",
      "title": "Teaching Project 1"
    },
    {
      "type": "image",
      "src": "./assets/photography/photography.png",
      "title": "Photography"
    },
    {
      "type": "image",
      "src": "./assets/physics-education/teaching_project_2.png",
      "title": "Teaching Project 2"
    },
    {
      "type": "image",
      "src": "./assets/science-communication/teaching_project_2.png",
      "title": "Teaching Project 2"
    },
    {
      "type": "image",
      "src": "./assets/stem-integration/teaching_project_2.png",
      "title": "Teaching Project 2"
    }
  ],
  "choreography": [
    {
      "type": "image",
      "src": "./assets/choreography/choreography.png",
      "title": "Choreography"
    }
  ],
  "creative-tools": [
    {
      "type": "image",
      "src": "./assets/creative-tools/creative_tools.png",
      "title": "Creative Tools"
    },
    {
      "type": "image",
      "src": "./assets/creative-tools/teaching_project_1.png",
      "title": "Teaching Project 1"
    }
  ],
  "curriculum-development": [
    {
      "type": "image",
      "src": "./assets/curriculum-development/teaching_project_1.png",
      "title": "Teaching Project 1"
    }
  ],
  "experiential-learning": [
    {
      "type": "image",
      "src": "./assets/experiential-learning/teaching_project_1.png",
      "title": "Teaching Project 1"
    }
  ],
  "photography": [
    {
      "type": "image",
      "src": "./assets/photography/photography.png",
      "title": "Photography"
    }
  ],
  "physics-education": [
    {
      "type": "image",
      "src": "./assets/physics-education/teaching_project_2.png",
      "title": "Teaching Project 2"
    }
  ],
  "science-communication": [
    {
      "type": "image",
      "src": "./assets/science-communication/teaching_project_2.png",
      "title": "Teaching Project 2"
    }
  ],
  "stem-integration": [
    {
      "type": "image",
      "src": "./assets/stem-integration/teaching_project_2.png",
      "title": "Teaching Project 2"
    }
  ]
};
