import os
import json

def build_gallery():
    assets_dir = './assets'
    media_data = {"all": []}
    
    # Valid media extensions
    valid_extensions = ('.png', '.jpg', '.jpeg', '.gif', '.webp', '.mp4', '.webm')
    
    # Iterate through folders inside assets
    for folder in os.listdir(assets_dir):
        folder_path = os.path.join(assets_dir, folder)
        
        if os.path.isdir(folder_path):
            media_data[folder] = []
            
            # Find all images/videos inside this folder
            for file in os.listdir(folder_path):
                if file.lower().endswith(valid_extensions):
                    ext = file.lower().split('.')[-1]
                    media_type = 'video' if ext in ('mp4', 'webm') else 'image'
                    
                    # Format a nice title based on filename
                    base_name = os.path.splitext(file)[0]
                    title = base_name.replace('_', ' ').replace('-', ' ').title()
                    
                    media_item = {
                        "type": media_type,
                        "src": f"./assets/{folder}/{file}",
                        "title": title
                    }
                    
                    media_data[folder].append(media_item)
                    media_data["all"].append(media_item)
    
    # Write to media.json
    with open('media.json', 'w', encoding='utf-8') as f:
        json.dump(media_data, f, indent=2)
        
    # Write to media.js for local file:// usage
    js_content = f"// Auto-generated by update_gallery.py\nlet mediaData = {json.dumps(media_data, indent=2)};\n"
    with open('media.js', 'w', encoding='utf-8') as f:
        f.write(js_content)

    print("Gallery successfully updated! media.json and media.js have been rebuilt.")

if __name__ == '__main__':
    build_gallery()
